apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data-pvc
  namespace: testing
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile-csi # Change this from default
  resources:
    requests:
      storage: 2Gi # Adjust size as needed

