# Copyright © 2026, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import yaml
import argparse
import os
import string
from string import Template
from frameworkLib import Framework

import logging

# Debug support
DEBUG_MODE = os.getenv('DEBUG_CREATETRANSFER', 'false').lower() == 'true'
if DEBUG_MODE:
    import debugpy
    debugpy.listen(5678)
    print("Waiting for debugger to attach on port 5678...")
    debugpy.wait_for_client()
    print("Debugger attached!")


# Configure logging
logging.basicConfig(
  format="%(asctime)s - %(levelname)-5s - %(name)s:%(lineno)-3d - %(message)s ",
  datefmt="%Y-%m-%d %H:%M",
  level=logging.INFO
  )
logging.getLogger().name = os.path.basename(__file__)

# Create an ArgumentParser object
parser = argparse.ArgumentParser(description="Argument parser")

# Add named arguments
parser.add_argument("-t", "--template", type=str, help="Custom Resource template file", required=True)
parser.add_argument("-a", "--artifactPath", type=str, help="Artifacts path", required=True)
parser.add_argument("-l", "--log_level", type=str, help="Output build path", required=False, default="INFO")

# Parse the arguments
args = parser.parse_args()

log_level=args.log_level.upper()
logging.getLogger().setLevel(log_level)
logging.info("Log Level set to: %s", log_level)

logging.info(f"Creating script to copy data to NFS mount")

# Read the environment variable
resources_setup = os.getenv("resourcesSetup")
resources_setup_dict = Framework.safe_json_loads(resources_setup)

nfs_dict = resources_setup_dict.get("nfs", "{}")

hostname = os.getenv("hostname")
pem_file = os.getenv("pemFile")
# nfs = os.getenv("nfs")

nfs_server = os.getenv("nfsServer")
nfs_user = os.getenv("nfsUser")
# nfs_root_folder = os.getenv("nfsRootFolder")

logging.info(f"Artifacts Path: {args.artifactPath}")
logging.info(f"Template: {args.template}")

# Load the nfs properties as a dictionary
# nfs_dict = Framework.safe_json_loads(nfs)

# Read the nfs properties into variables
# server = nfs_dict.get("server")
# user = nfs_dict.get("user")
scenario_data_source_location = os.getenv("scenarioDataSourceLocation")
data_sources = nfs_dict.get("data-sources", [])
nfs_root_folder = nfs_dict.get("root-folder", [])

# Print the values of the variables for debugging purposes
logging.debug(f"NFS variables:")
logging.debug(f"  server: {nfs_server}")
logging.debug(f"  user: {nfs_user}")
logging.debug(f"  nfs_root_folder: {nfs_root_folder}")
logging.debug(f"  scenario_data_source_location: {scenario_data_source_location}")
logging.debug(f"  data_sources: {data_sources}")

# Read the template file
with open(args.template, 'r') as file:
  templateFile = file.read()

create_folders_template = string.Template(templateFile)

# Transform the data files array into a space separated string
data_source_names_string = " ".join(data_source.get("name") for data_source in data_sources if "name" in data_source)
logging.info(f"data_source_names_string: {data_source_names_string}")

with open(os.path.join(args.artifactPath, "dataTransfer.sh" ), "w") as file:

  file.write(f"#!/usr/bin/env bash\n\n")
  file.write(f"## NOTE: This file is generated by createDataTransferScript.py and will be overwritten. ##\n\n")

  if not data_sources:
      file.write("# No data transfers configured\n")
      logging.info("No data transfers configured.")
  else:
    for data_source in data_sources:
  
      name = data_source.get("name")
      # source_folder = data_source.get("source-folder")
      dest_folder = os.path.join(nfs_root_folder, data_source.get("destination-folder"))
      source = os.path.join(scenario_data_source_location, name)
      destination = os.path.join(nfs_root_folder, dest_folder, name)    
  
      logging.info(f"data_source: ")
      logging.info(f"  name: {name}")
      logging.info(f"  source_folder: {scenario_data_source_location}")
      logging.info(f"  dest_folder: {dest_folder}")
  
      create_folders_doc = create_folders_template.substitute(pem_file=pem_file, server=nfs_server, user=nfs_user, source=source, dest_folder=dest_folder, destination=destination)
      file.write(create_folders_doc)

  file.close()

  # Make the script executable
  os.chmod(os.path.join(args.artifactPath, "dataTransfer.sh"), 0o755)

