# Copyright © 2026, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import yaml
import argparse
import os
import string
from string import Template
from frameworkLib import Framework
import logging

# Debug support
DEBUG_MODE = os.getenv('DEBUG_CREATEFOLDERS', 'false').lower() == 'true'
if DEBUG_MODE:
    import debugpy
    debugpy.listen(5678)
    print("Waiting for debugger to attach on port 5678...")
    debugpy.wait_for_client()
    print("Debugger attached!")

# Configure logging
logging.basicConfig(
  format="%(asctime)s - %(levelname)-5s - %(name)s:%(lineno)-3d - %(message)s ",
  datefmt="%Y-%m-%d %H:%M",
  level=logging.INFO
  )
logging.getLogger().name = os.path.basename(__file__)

# Create an ArgumentParser object
parser = argparse.ArgumentParser(description="Argument parser")

# Add named arguments
parser.add_argument("-t", "--template", type=str, help="Custom Resource template file", required=True)
parser.add_argument("-a", "--artifactPath", type=str, help="Artifacts path", required=True)
parser.add_argument("-l", "--log_level", type=str, help="Output build path", required=False, default="INFO")

# Parse the arguments
args = parser.parse_args()

log_level=args.log_level.upper()
logging.getLogger().setLevel(log_level)
logging.info("Log Level set to: %s", log_level)

logging.info(f"Creating script to create folders on NFS mount")

# Read the environment variable
hostname = os.getenv("hostname")
pem_file = os.getenv("pemFile")
# nfs = os.getenv("nfs")

##
resources_setup = os.getenv("resourcesSetup")
resources_setup_dict = Framework.safe_json_loads(resources_setup)

nfs_dict = resources_setup_dict.get("nfs", "{}")

#
# #
nfs_server = os.getenv("nfsServer")
nfs_user = os.getenv("nfsUser")
# nfs_root_folder = os.getenv("nfsRootFolder")

logging.info(f"Artifacts Path: {args.artifactPath}")
logging.info(f"Template: {args.template}")

# Load the nfs properties as a dictionary
# nfs_dict = Framework.safe_json_loads(nfs)

# Read the nfs properties into variables
# server = nfs_dict.get("server")
# user = nfs_dict.get("user")
folders = nfs_dict.get("folders", [])
nfs_root_folder = nfs_dict.get("root-folder", [])

# Print the values of the variables for debugging purposes
logging.debug(f"NFS variables:")
logging.debug(f"  server: {nfs_server}")
logging.debug(f"  user: {nfs_user}")
logging.debug(f"  root_folder: {nfs_root_folder}")
logging.debug(f"  folders: {folders}")

# Read the template file
with open(args.template, 'r') as file:
  templateFile = file.read()

create_folders_template = string.Template(templateFile)

# Transform the folders array into a space separated string
dir_names_string = " ".join(folder.get("name") for folder in folders if "name" in folder)
logging.info(f"dir_names_string: {dir_names_string}")

with open(os.path.join(args.artifactPath, "createFolders.sh" ), "w") as file:

  if dir_names_string.strip():
    # Normal case: directories to create
    create_folders_doc = create_folders_template.substitute(pem_file=pem_file, server=nfs_server, user=nfs_user, root_folder=nfs_root_folder, dir_names_string=dir_names_string)
    file.write(create_folders_doc)
  else:
    # Empty case: no directories to create
    file.write("#!/usr/bin/env bash\n\n")
    file.write("## NOTE: This file is generated by createFolders.py and will be overwritten. ##\n\n")
    file.write("# No directories to create - the folders list was empty\n")

  file.close

  #Ensrue the script is executable
  os.chmod(os.path.join(args.artifactPath, "createFolders.sh"), 0o755)
