# Copyright © 2026, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import yaml
import argparse
import os
import string
import logging

# Configure logging
logging.basicConfig(
  format="%(asctime)s - %(levelname)-5s - %(name)s:%(lineno)-3d - %(message)s ",
  datefmt="%Y-%m-%d %H:%M",
  level=logging.INFO
  )
logging.getLogger().name = os.path.basename(__file__)

# Create an ArgumentParser object
parser = argparse.ArgumentParser(description="Argument parser")

# Add named arguments
parser.add_argument("-a", "--artifactPath", type=str, help="Artifacts path", required=True)
parser.add_argument("-l", "--log_level", type=str, help="Output build path", required=False, default="INFO")

# Parse the arguments
args = parser.parse_args()

log_level=args.log_level.upper()
logging.getLogger().setLevel(log_level)
logging.info("Log Level set to: %s", log_level)

logging.info(f"Creating custom resources")

# Read the environment variable
frameworkScriptsLocationFullPath = os.getenv("frameworkScriptsLocationFullPath")

logging.info(f"Artifacts Path: {args.artifactPath}")

with open(os.path.join(args.artifactPath, "runScenarioConfig.sh" ), "w") as file:
  file.write(f"#!/usr/bin/env bash\n")
  file.write(f"## NOTE: This file is generated by createDataTransferScript.py and will be overwritten. ##\n\n")


  file.write(f"mkdir -p logs \n")
  file.write(f"exec 3>&1 4>&2 \n")
  file.write(f"trap 'exec 2>&4 1>&3' 0 1 2 3 \n")
  file.write(f"exec > >(tee -a ./logs/runScenarioConfig_`date +%Y%m%d%H%M%S`.log) 2>&1 \n\n")
  
  file.write(f"echo \"Running Scenario Config\"\n")
  file.write(f"echo \"Artifacts Path: {args.artifactPath}\"\n")
  file.write(f"echo \"Framework Resources Location: {frameworkScriptsLocationFullPath}\"\n\n")

  file.write(f"{args.artifactPath}/createFolders.sh \n")
  file.write(f"if [ $? -ne 0 ]; then \n")
  file.write(f"  echo \"ERROR: Failed to create folders. [createFolders.sh] Exiting.\" \n")
  file.write(f"  exit 1 \n")
  file.write(f"fi \n\n")

  file.write(f"{args.artifactPath}/dataTransfer.sh \n")
  file.write(f"if [ $? -ne 0 ]; then \n")
  file.write(f"  echo \"ERROR: Transferring data. [dataTransfer.sh] Exiting.\" \n")
  file.write(f"  exit 1 \n")
  file.write(f"fi \n\n")

  file.write(f"{args.artifactPath}/createCasLibs.sh \n")
  file.write(f"if [ $? -ne 0 ]; then \n")
  file.write(f"  echo \"ERROR: Creating caslibs. [createCasLibs.sh] Exiting.\" \n")
  file.write(f"  exit 1 \n")
  file.write(f"fi \n\n")

  file.write(f"{args.artifactPath}/loadTables.sh \n")
  file.write(f"if [ $? -ne 0 ]; then \n")
  file.write(f"  echo \"ERROR: Loading tables. [loadTables.sh] Exiting.\" \n")
  file.write(f"  exit 1 \n")
  file.write(f"fi \n\n")

  # Disable Model Studio project import for now
  # file.write(f"{args.artifactPath}/importModelStudioProject.sh \n")
  # file.write(f"if [ $? -ne 0 ]; then \n")
  # file.write(f"  echo \"ERROR: Importing Model Studio projects. [importModelStudioProject.sh] Exiting.\" \n")
  # file.write(f"  exit 1 \n")
  # file.write(f"fi \n\n")

#Make the script executable
os.chmod(os.path.join(args.artifactPath, "runScenarioConfig.sh"), 0o755)
