# Copyright © 2026, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import yaml
import argparse
import os
import string
from string import Template
from frameworkLib import Framework
import logging

# Debug support
DEBUG_MODE = os.getenv('DEBUG_CREATECASLIBS', 'false').lower() == 'true'
if DEBUG_MODE:
    import debugpy
    debugpy.listen(5678)
    print("Waiting for debugger to attach on port 5678...")
    debugpy.wait_for_client()
    print("Debugger attached!")

# Configure logging
logging.basicConfig(
  format="%(asctime)s - %(levelname)-5s- %(name)s:%(lineno)-3d - %(message)s ",
  datefmt="%Y-%m-%d %H:%M",
  level=logging.INFO
  # force=True  
  )
logging.getLogger().name = os.path.basename(__file__)

# Create an ArgumentParser object
parser = argparse.ArgumentParser(description="Argument parser")

# Add named arguments
parser.add_argument("-t", "--createCasLibTemplate", type=str, help="Create CasLib template file", required=True)
parser.add_argument("-u", "--createLoadTabletemplate", type=str, help="Create load table template file", required=True)
parser.add_argument("-a", "--artifactPath", type=str, help="Artifacts path", required=True)
parser.add_argument("-l", "--log_level", type=str, help="Output build path", required=False, default="INFO")

# Parse the arguments
args = parser.parse_args()

log_level=args.log_level.upper()
logging.getLogger().setLevel(log_level)
logging.info("Log Level set to: %s", log_level)
logging.info(f"Creating script to create CasLibs")

# Read the environment variable
frameworkResourcesLocation = os.getenv("frameworkResourcesLocation")

resources_setup = os.getenv("resourcesSetup")
resources_setup_dict = Framework.safe_json_loads(resources_setup)

#cas = os.getenv("cas")
cas_dict = resources_setup_dict.get("cas", "{}")
cli_profile = os.getenv("viyaCliProfile")
#nfs = os.getenv("nfs")
nfs_dict = resources_setup_dict.get("nfs", "{}")
#cas_server = os.getenv("casServer")
cas_server = resources_setup_dict.get("cas-server", "cas-shared-default")


logging.info(f"Artifacts Path: {args.artifactPath}")
logging.info(f"Create CasLib Template: {args.createCasLibTemplate}")
logging.info(f"Create Load Table Template: {args.createLoadTabletemplate}")

# Load the nfs properties as a dictionary

# Robustly load cas_dict and nfs_dict as dictionaries
# cas_dict = Framework.safe_json_loads(cas)
# nfs_dict = Framework.safe_json_loads(nfs)

# Read the nfs properties into variables
data_location = cas_dict.get("data-location") 
source_data_location = os.getenv("scenarioDataSourceLocation")
allow_list = cas_dict.get("allow-list", [])
create_libs = cas_dict.get("create-libs", [])
data_sources = nfs_dict.get("data-sources", [])

# Print the values of the variables for debugging purposes
logging.debug(f"NFS variables:")
logging.debug(f"  cas_server: {cas_server}")
logging.debug(f"  data_location: {data_location}")
logging.debug(f"  source_data_location: {source_data_location}")
logging.debug(f"  allow_list: {allow_list}")
logging.debug(f"  create_libs: {create_libs}")

# Read the template file
with open(args.createCasLibTemplate, 'r') as file:
  templateFile = file.read()

  create_caslibs_template = string.Template(templateFile)

  with open(os.path.join(args.artifactPath, "createCasLibs.sh" ), "w") as file:

    file.write(f"#!/usr/bin/env bash\n\n")
    file.write(f"## NOTE: This file is generated by createCasLibs.py and will be overwritten. ##\n\n")

    file.write("## Ensure admin cli is authenticated by calling simple command\n")
    file.write(f"result=$(sas-viya --profile {cli_profile} -k cas servers list 2>&1) \n")
    file.write("if echo \"$result\" | grep -q \"Please login before attempting any commands\"; then \n")
    file.write("        echo \"ERROR: SAS Admin CLI authentication seems to be invalid \" \n")
    file.write("        echo \"ERROR: $result\" \n")
    file.write("        exit 1 \n")
    file.write("else \n")
    file.write("        echo \"SAS Admin CLI authentication successful.\" \n")
    file.write("fi \n\n")

    if not allow_list:
      logging.info("No paths to add to the allow list.")
      file.write("# No paths to add to the allow list\n")
    else:
      file.write(f"# Add paths to the allow list #\n\n")
      for allow_path in allow_list:
        allow_path_string = allow_path.get("path")
        logging.info(f"allow_path_string: {allow_path_string}")
        file.write(f"sas-viya --profile {cli_profile} -k cas servers paths-list add-paths --server {cas_server} --path {allow_path_string} \n")

    if not create_libs:
      file.write("# No caslibs to create\n")
      logging.info("No caslibs to create.")
    else:
      for caslib in create_libs:
        name = caslib.get("name")
        path = caslib.get("path")
        logging.debug(f"name: {name}")
        logging.debug(f"path: {path}")

        create_caslibs_doc = create_caslibs_template.substitute(server=cas_server, cli_profile=cli_profile, name=name, path=path)
        file.write(create_caslibs_doc)

  #Ensure the script is executable
  os.chmod(os.path.join(args.artifactPath, "createCasLibs.sh"), 0o755)

# Create the script that optionally loads tables
logging.debug(f"Creating script to load tables (loadTables.sh)\n")
with open(args.createLoadTabletemplate, 'r') as file:
  
  templateFile = file.read()
  create_load_tables_template = string.Template(templateFile)

  with open(os.path.join(args.artifactPath, "loadTables.sh" ), "w") as file:
    
    file.write(f"#!/usr/bin/env bash\n\n")
    file.write(f"## NOTE: This file is generated by createCasLibs.py and will be overwritten. ##\n\n")
  
    if not data_sources:
      file.write("# No data to load\n")
      logging.info("No data sources found. No data to load.")
    else:
      for data_source in data_sources:
        table_name = data_source.get("name")
        caslib = data_source.get("destination-cas-lib")
        logging.debug(f"table_name: {table_name}")
        logging.debug(f"caslib: {caslib}")

        create_load_tables_doc = create_load_tables_template.substitute(cli_profile=cli_profile, server=cas_server, name=caslib, table_name=table_name)
        file.write(create_load_tables_doc)
        
    file.close
    # Ensure the script is executable
    os.chmod(os.path.join(args.artifactPath, "loadTables.sh"), 0o755)    

    
