# Copyright © 2026, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import yaml
import argparse
import os
import string
from string import Template
import logging

# Configure logging
logging.basicConfig(
  format="%(asctime)s - %(levelname)-5s - %(name)s:%(lineno)-3d - %(message)s ",
  datefmt="%Y-%m-%d %H:%M",
  level=logging.INFO
  )
logging.getLogger().name = os.path.basename(__file__)

# Create an ArgumentParser object
parser = argparse.ArgumentParser(description="Argument parser")

# Add named arguments
parser.add_argument("-a", "--artifactPath", type=str, help="Artifacts path", required=True)
parser.add_argument("-r", "--scenario_path", type=str, help="Scenario base path", required=True)
parser.add_argument("-p", "--build_path", type=str, help="Output build path", required=True)
parser.add_argument("-l", "--log_level", type=str, help="Output build path", required=False, default="INFO")

# Parse the arguments
args = parser.parse_args()

log_level=args.log_level.upper()
logging.getLogger().setLevel(log_level)
logging.info("Log Level set to: %s", log_level)

logging.info(f"Creating script to create CasLibs")

# Read the environment variable
frameworkResourcesLocation = os.getenv("frameworkResourcesLocation")
cas = os.getenv("cas")
cli_profile = os.getenv("viyaCliProfile")
nfs = os.getenv("nfs")
cas_server = os.getenv("casServer")


logging.info(f"Artifacts Path: {args.artifactPath}")
logging.info(f"Create CasLib Template: {args.createCasLibTemplate}")
logging.info(f"Create Load Table Template: {args.createLoadTabletemplate}")

# Load the nfs properties as a dictionary
cas_dict = json.loads(cas)
nfs_dict = json.loads(nfs)

# Read the nfs properties into variables
data_location = cas_dict.get("data-location")
source_data_location = cas_dict.get("source-data-location")
allow_list = cas_dict.get("allow-list", [])
create_libs = cas_dict.get("create-libs", [])
data_sources = nfs_dict.get("data-sources", [])

# Print the values of the variables for debugging purposes
logging.info(f"NFS variables:")
logging.info(f"  cas_server: {cas_server}")
logging.info(f"  data_location: {data_location}")
logging.info(f"  source_data_location: {source_data_location}")
logging.info(f"  allow_list: {allow_list}")
logging.info(f"  create_libs: {create_libs}")

# Read the template file
with open(args.createCasLibTemplate, 'r') as file:
  templateFile = file.read()

  create_caslibs_template = string.Template(templateFile)

  with open(os.path.join(args.artifactPath, "createCasLibs.sh" ), "w") as file:

    file.write(f"#!/usr/bin/env bash\n\n")
    file.write(f"## NOTE: This file is generated by createCasLibs.py and will be overwritten. ##\n\n")

    file.write(f"# Add paths to the allow list #\n\n")
    for allow_path in allow_list:
      allow_path_string = allow_path.get("path")
      logging.info(f"allow_path_string: {allow_path_string}")

      file.write(f"sas-viya --profile {cli_profile} -k cas servers paths-list add-paths --server {cas_server} --path {allow_path_string} \n")

    for caslib in create_libs:
      name = caslib.get("name")
      path = caslib.get("path")
      logging.info(f"name: {name}")
      logging.info(f"path: {path}")

      create_caslibs_doc = create_caslibs_template.substitute(server=cas_server, cli_profile=cli_profile, name=name, path=path)
      file.write(create_caslibs_doc)
      file.close

  #Ensure the script is executable
  os.chmod(os.path.join(args.artifactPath, "createCasLibs.sh"), 0o755)

# Create the script that optionally loads data
logging.info(f"Creating script to load data\n")
with open(args.createLoadTabletemplate, 'r') as file:
  
  templateFile = file.read()
  create_load_tables_template = string.Template(templateFile)

  with open(os.path.join(args.artifactPath, "loadTables.sh" ), "w") as file:
    
    file.write(f"#!/usr/bin/env bash\n\n")
    file.write(f"## NOTE: This file is generated by createCasLibs.py and will be overwritten. ##\n\n")
  
    for data_source in data_sources:
      table_name = data_source.get("name")
      caslib = data_source.get("destination-cas-lib")
      logging.info(f"table_name: {table_name}")
      logging.info(f"caslib: {caslib}")

      create_load_tables_doc = create_load_tables_template.substitute(cli_profile=cli_profile, server=cas_server, name=caslib, table_name=table_name)
      file.write(create_load_tables_doc)
        
    file.close
    # Ensure the script is executable
    os.chmod(os.path.join(args.artifactPath, "loadTables.sh"), 0o755)    

    
