# Copyright © 2026, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import os
import yaml
import sys
import argparse
import json
import logging

# Configure logging
# logging.basicConfig(level=logging.INFO)
logging.basicConfig(
  format="{levelname} - {asctime} - {message}",
  style="{",
  datefmt="%Y-%m-%d %H:%M",
  level=logging.INFO
)

# Perform check to ensure that the required libraries are installed
try:
  from deepmerge import Merger
except ImportError:
  logging.error("The deepmerge library is not installed. Please install it by running 'pip install deepmerge'")
  sys.exit(1)


# Create an ArgumentParser object
parser = argparse.ArgumentParser(description="Argument parser")

# Add named arguments
parser.add_argument("-g", "--global_config", type=str, help="Global configuration file path", required=True)
parser.add_argument("-w", "--workload_config", type=str, help="Workload configuration file path")
parser.add_argument("-s", "--scenario_config", type=str, help="Scenario configuration file path")
parser.add_argument("-d", "--framework_defaults", type=str, help="Framework defaults path" )
parser.add_argument("-u", "--users_file", type=str, help="Users file path", required=False, default="none")
parser.add_argument("-p", "--build_path", type=str, help="Output build path", required=True)

# Parse the arguments
args = parser.parse_args()

# Check if the log level is set in the environment variable, if not set it to the default INFO level
log_level = os.getenv("logLevel", "INFO").upper()
logging.getLogger().setLevel(log_level)
  
# Function to load YAML file and set environment variables
def set_env_from_yaml(args):

  global_config_file = args.global_config
  workload_config_file = args.workload_config
  scenario_config_file = args.scenario_config
  framework_defaults_file = args.framework_defaults

  if workload_config_file and not os.path.exists(workload_config_file):
    logging.error(f"File {workload_config_file} does not exist")
    sys.exit(1)

  if scenario_config_file and not os.path.exists(scenario_config_file):
    logging.error(f"File {scenario_config_file} does not exist")
    sys.exit(1)

  if framework_defaults_file and not os.path.exists(framework_defaults_file):
    logging.error(f"File {framework_defaults_file} does not exist")
    sys.exit(1)

  if not os.path.exists(global_config_file):
    logging.error(f"File {global_config_file} does not exist")
    sys.exit(1)

  if workload_config_file:
    logging.info(f"Merging configuration files: {global_config_file} and {workload_config_file}")
    config_file_contents = merge_yaml_files(global_config_file, workload_config_file, framework_defaults_file, 'workload-definition')  
  elif scenario_config_file:
    logging.info(f"Merging configuration files: {global_config_file} and {scenario_config_file}")
    config_file_contents = merge_yaml_files(global_config_file, scenario_config_file, framework_defaults_file, 'scenario-config')

  output_file_path = os.path.join(args.build_path,  'setVariables.sh')
  with open(output_file_path, 'w') as output_file:

    logging.info(f"Writing global environment variables to {output_file_path}")
    output_file.write(f"#!/usr/bin/env bash \n\n")
    output_file.write(f"## NOTE: This file is generated by loadConfiguration.py and will be overwritten. ##\n\n")

    framework_scripts_location_full_path = os.getenv("frameworkScriptsLocationFullPath")
    output_file.write(f"export frameworkScriptsLocationFullPath={framework_scripts_location_full_path}\n")

    scenarios_location_full_path = os.getenv("scenariosLocationFullPath")
    output_file.write(f"export scenariosLocationFullPath={scenarios_location_full_path}\n")

    users_file_full_path = args.users_file
    output_file.write(f"export usersFileFullPath={users_file_full_path}\n")

    ## TODO This is part of the reource setup scripting and yet available
    # auth_refresh_token = get_refresh_token(global_config_file)
    # output_file.write(f"export authRefreshToken={auth_refresh_token}\n\n")

    # Get the workloads-global-config environment variables
    write_config_variables(output_file, config_file_contents)    

## TODO Not available yet
def get_refresh_token(global_config_file):

  # Read the auth-type from the global config file, if it is set to SCIM, then we need to get the refresh token from the credentials file
  with open(global_config_file, 'r') as file:
    global_config = yaml.safe_load(file)
    global_config = global_config.get("global-config", {})
    auth_type = global_config.get("auth-type", None)
    viya_cli_profile = global_config.get("viya-cli-profile", None)
  
  if not auth_type:
    logging.error("auth-type is not set in the global config file.")
    sys.exit(1)

  if str(auth_type).upper() != "SCIM":
    logging.error("No refresh token is required for this auth-type.")
    return None
  
  if not viya_cli_profile:
    logging.error("viya-cli-profile is not set in the global config file.")
    sys.exit(1)

  # Read the contents of ~/.sas/credentials.json
  credentials_file_path = os.path.expanduser("~/.sas/credentials.json")
  if not os.path.exists(credentials_file_path):
    logging.error(f"Credentials file not found at {credentials_file_path}.")
    sys.exit(1)

  with open(credentials_file_path, 'r') as file:
    credentials = json.load(file)
    if not credentials:
      logging.error(f"Error: Credentials file is empty at {credentials_file_path}.")
      sys.exit(1)

    #Get the "Default"."refresh_token" value from the json file
    logging.debug(f"Reading refresh token from credentials file at {credentials_file_path} for profile: {viya_cli_profile}")
    profile_contents = credentials.get(viya_cli_profile, {}) #.get("access_token", None)
    refresh_token = profile_contents.get("refresh-token")

    if not refresh_token:
      logging.error(f"Error: Refresh token not found for key: {viya_cli_profile}.")
      sys.exit(1)

    logging.debug(f"Found refresh token for profile {viya_cli_profile}: {refresh_token}")  

    return refresh_token

  return credentials.get("refresh_token", None)
    
def merge_yaml_files(base_file, merge_file, defaults_file, parent_node):
  # Define merging strategy.
  merger = Merger(
    [(dict, ["merge"]), (list, ["append"])],  # Merge dictionaries, append lists
    ["override"],  # Fallback strategy
    ["override"]  # Conflict resolution strategy
  )

  # Check if an optional file is provided and exists
  optional_file = args.optional_file if hasattr(args, 'optional_file') else None
  if optional_file and os.path.exists(optional_file):
    with open(optional_file, 'r') as file4:
      optional_file_content = yaml.safe_load(file4)
      optional_file_content = optional_file_content.get("optional-config", {})
      # Merge the optional file content
      base_file = merger.merge(base_file, optional_file_content)

  with open(base_file, 'r') as file1:
    base_file = yaml.safe_load(file1)
    base_file = base_file.get("global-config", {})

  with open(merge_file, 'r') as file2:
    scenario_file = yaml.safe_load(file2)  
    scenario_file = scenario_file.get(parent_node, {})

  merged_config = merger.merge(base_file, scenario_file)

  if defaults_file:
    logging.info(f"Merging defaults file: {defaults_file}")    
    with open(defaults_file, 'r') as file10:
      defaults_file_contents = yaml.safe_load(file10)  
      merged_config = merger.merge(merged_config, defaults_file_contents)
  
  return merged_config
  
def write_config_variables(output_file, env_vars):
  for key, value in env_vars.items():
    camel_case_key = ''.join(word.capitalize() if i != 0 else word for i, word in enumerate(key.split('-')))
    json_value = json.dumps(value)
    output_file.write(f"export {camel_case_key}=$(jq -r '.' <<< '{json_value}')\n")     

#Run the function
logging.info("Loading configuration and setting environment variables...")
set_env_from_yaml(args)
